# Plugins are rather limited in Github Pages, though a lot of useful ones are supported, check out:
# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-redirect-from

####################
###### routes ######
####################

url: https://safing.io
base_url: "/" # the subpath of your site, e.g. /blog

### assets
assets_url: /assets/
img_url: /assets/img/
vendor_url: /vendor/

### pages
about_url: /about/
blog_url: /blog/
community_hub_url: /community-hub/
contact_url: /contact/
help_url: /help/
newsletter_url: /newsletter/
ownership_url: /ownership/
podcast_url: /podcast/
portmaster_url: /portmaster/
privacy_url: /privacy/
spn_url: /spn/
team_url: /team/
technology_url: /technology/
terms_url: /terms/
whitepaper_url: /files/whitepaper/

### external
download_windows_url: https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe
download_linux_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb

github_windows_wiki: https://github.com/safing/portmaster/wiki/Windows
github_linux_wiki: https://github.com/safing/portmaster/wiki/Linux

company_agreement_url: https://www.firmenmonitor.at/Secure/CompanyDetail.aspx?CID=761761
github_url: https://github.com/Safing
kickstarter_url: https://www.kickstarter.com/projects/safingio/spn
reddit_url: https://reddit.com/r/safing
twitter_url: https://twitter.com/SafingIO

### donations
donations:
  bitcoin:
    url: https://www.blockchain.com/btc/address/1AosdDyzd8PVUFTUEXoaJHTyPVHuKQxdmq?filter=2
  paypal:
    url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2QHNM78H9YC9L&source=url

###########################
###### site settings ######
###########################

title: Safing
encoding: "utf-8"
lang: "en"
description: > # this means to ignore newlines until "base_url:"
  Safing is a software that protects your privacy online. It's so easy, anyone can use it.

markdown: kramdown

excerpt_separator: "<!--break-->"
inter_post_navigation: false

email: hello@safing.io
emailobfuscated: "=b!isfg>#nbjmup;ifmmpAtbgjoh/jp#?ifmmpAtbgjoh/jp=0b?"

communities:
  - reddit:
    name: Reddit
    icon: reddit
    username: r/safing
    url: https://reddit.com/r/safing
    desc: Join our Reddit
  - github:
    name: GitHub
    icon: github
    username: Safing
    url: https://github.com/Safing
    desc: Fork us on GitHub
  - twitter:
    name: Twitter
    icon: twitter
    username: SafingIO
    url: https://twitter.com/SafingIO
    desc: Follow me on Twitter

###################################
###### media/content options ######
###################################

collections:
  podcasts:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      type: "post"
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "podcast"
      permalink: /podcast/:year/:month/:day/:title/
      type: "podcast"

##############################
###### Podcast settings ######
##############################

podcast_itunes_url: https://podcasts.apple.com/podcast/id1480027286
podcast_feed_url: /podcast.xml
podcast_album_art: /assets/podcast/img/cover.jpg
podcast_owner: 'Safing'
podcast_email: 'hello@safing.io'
podcast_category: Business
podcast_subcategory_one: Entrepreneurship
podcast_explicit: "no"
podcast_author: safing.io
podcast_title: The Safing Podcast
podcast_subtitle: "The venture of a company forging powerful privacy tools."
podcast_description: "Join the founders on their mission to help everyone withstand today's mass surveillance so you reclaim your privacy. Have a look behind the scenes to be the first to know what's coming up! If you like what you hear, consider contributing to the community."
podcast_summary: "Join the founders on their mission to help everyone withstand today's mass surveillance so you reclaim your privacy. Have a look behind the scenes to be the first to know what's coming up! If you like what you hear, consider contributing to the community."
