# Plugins are rather limited in Github Pages, though a lot of useful ones are supported, check out:
# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-redirect-from

####################
###### routes ######
####################

url: https://safing.io
base_url: "/" # the subpath of your site, e.g. /blog

### assets
assets_url: /assets/
img_url: /assets/img/
vendor_url: /vendor/

### pages
about_url: /about/
blog_url: /blog/
backlog_url: /backlog/
community_hub_url: /community-hub/
contact_url: /contact/
esa_bic_url: /esa-bic/
help_url: /support/
newsletter_url: /newsletter/
ownership_url: /ownership/
business_model_url: /business-model/
podcast_url: /podcast/
portmaster_url: /portmaster/
privacy_url: /privacy/
next_page_url: /next/
spn_url: /spn/
team_url: /team/
terms_url: /terms/
video_url: /video/
whitepaper_url: /files/whitepaper/Gate17.pdf
vpn_comparison_url: /blog/2020/01/22/how-the-spn-compares-to-vpns/
tor_comparison_url: /blog/2020/01/22/how-the-spn-compares-to-tor/

### external
account_server_url: https://account.safing.io/
assets_server_url: https://assets.safing.io/
company_agreement_url: https://www.firmenmonitor.at/Secure/CompanyDetail.aspx?CID=761761
download_linux_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb
download_windows_url: https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe
github_url: https://github.com/safing
github_linux_wiki_url: https://github.com/safing/portmaster/wiki/Linux
github_windows_wiki_url: https://github.com/safing/portmaster/wiki/Windows
invidious_channel_url: https://invidio.us/channel/UC_6TW053IlS4M22g7CxnukA
kickstarter_url: https://www.kickstarter.com/projects/safingio/spn
reddit_url: https://reddit.com/r/safing
twitter_url: https://twitter.com/SafingIO
youtube_channel_url: https://www.youtube.com/channel/UC_6TW053IlS4M22g7CxnukA
docs_url: https://docs.safing.io/

### donations
donations:
  bitcoin:
    url: https://www.blockchain.com/btc/address/1AosdDyzd8PVUFTUEXoaJHTyPVHuKQxdmq?filter=2
  paypal:
    url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2QHNM78H9YC9L&source=url

###########################
###### site settings ######
###########################

title: Safing
encoding: "utf-8"
lang: "en"
description: > # this means to ignore newlines until "base_url:"
  Safing is a software that protects your privacy online. It's so easy, anyone can use it.

markdown: kramdown

excerpt_separator: "<!--break-->"
inter_post_navigation: false

email: hello@safing.io
emailobfuscated: "=b!isfg>#nbjmup;ifmmpAtbgjoh/jp#?ifmmpAtbgjoh/jp=0b?"

###################################
###### media/content options ######
###################################

collections:
  podcasts:
    output: true
  videos:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      type: "post"
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "podcast"
      permalink: /podcast/:year/:month/:day/:title/
      type: "podcast"
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
      permalink: /video/:year/:month/:day/:title/
      type: "video"

##############################
###### Podcast settings ######
##############################

podcast_itunes_url: https://podcasts.apple.com/podcast/id1480027286
podcast_feed_url: /podcast.xml
podcast_album_art: /assets/podcast/img/cover.jpg
podcast_owner: 'Safing'
podcast_email: 'hello@safing.io'
podcast_category: Business
podcast_subcategory_one: Entrepreneurship
podcast_explicit: "no"
podcast_author: safing.io
podcast_title: "Coding Freedom - The Safing Podcast"
podcast_subtitle: "Join ordinary people who fight Mass Surveillance because they Love Freedom."
podcast_description: "Discontent with the global state of mass surveillance and its negative impact on our lives, the Safing team decided it was time to do something about it. Take part of the journey and explore the behind-the-scenes: How do you fund a privacy company? Why are deadlines always unrealistic? And ultimately, what is the solution to the privacy dilemma?"
podcast_summary: "Discontent with the global state of mass surveillance and its negative impact on our lives, the Safing team decided it was time to do something about it. Take part of the journey and explore the behind-the-scenes: How do you fund a privacy company? Why are deadlines always unrealistic? And ultimately, what is the solution to the privacy dilemma?"
