# to start the server just run
# docker-compose up
jekyll:
  image: jekyll/jekyll:4.2.2
  command: jekyll serve --watch --incremental --livereload --future
  ports:
    - 4000:4000
    - 35729:35729
  volumes:
    - .:/srv/jekyll
